project_id = "wqtnmwuvpkvcwttxdgvv"

[functions.initialize-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.generate-legal-document]
verify_jwt = true

[functions.generate-contract]
verify_jwt = true

[functions.send-sales-inquiry]
verify_jwt = false

[functions.send-sms-reminder]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-sms-otp]
verify_jwt = false

[functions.verify-sms-otp]
verify_jwt = false
